# Generated by Django 3.2.9 on 2021-11-30 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=150)),
                ('salt_value', models.CharField(max_length=500)),
                ('user_pass', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.countydepartments')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidencesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('name_of_complainant', models.CharField(default='Anonymous', max_length=25)),
                ('incident_type', models.CharField(max_length=25)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('gender', models.CharField(max_length=10)),
                ('subcounty', models.CharField(blank=True, default='Not Specified', max_length=20)),
                ('wards', models.CharField(blank=True, max_length=25)),
                ('email_of_complainant', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('incident_report_date', models.CharField(max_length=50)),
                ('incident_occurrence_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('assigned_to', models.ManyToManyField(to='incidents.CountyUsers')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.countydepartments')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.incidentstatus')),
            ],
            options={
                'ordering': ['-incident_occurrence_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=1000)),
                ('date_of_reply', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ManyToManyField(to='incidents.IncidencesTable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.countyusers')),
            ],
        ),
    ]
