# Generated by Django 3.2.9 on 2021-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20211216_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
